/* 
  Sketch generated by the Arduino IoT Cloud Thing "lava_ruka"
  https://create.arduino.cc/cloud/things/cac4404c-3a90-49a6-af82-48a557ef6c7c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool finger;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include <Servo.h>

#define PRST_PIN 3
#define OHNI 90
#define VYSTRI 0

Servo myservo;
int servo_pozicia = VYSTRI;

void setup(){
  Serial.begin(9600); // inicializácia seriovej komunikácie
  myservo.attach(PRST_PIN);
  myservo.write(servo_pozicia);
  delay(1000); // oneskorenie dáva možnosť čakať na sériový monitor bez blokovania, ak sa žiadny nenájde

  // definované v thingProperties.h
  initProperties();

  // pripojenie na Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // umožňuje získavať informácie a chyby spojené zo sieťou a IoT cloud
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop(){
  ArduinoCloud.update(); 

  int i;

  if((finger == 0) && (servo_pozicia == OHNI)){
    for(i = 90; i >= VYSTRI; i--){ // postupné vystretie prstu
      myservo.write(i);
      delay(10);
    }
    servo_pozicia = 0;
  } else if((finger == 1) && (servo_pozicia == VYSTRI)){
    for(i = 0; i <= 90; i++){ // postupné ohnutie prstu
      myservo.write(i);
      delay(10);
    }
    servo_pozicia = 90;
  }
}

/*
  Since Finger is READ_WRITE variable, onFingerChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFingerChange()  {
  // Add your code here to act upon Finger change
}
